services:
  cassandra:
    image: cassandra:4.1.4
    container_name: cassandra
    user: root
    ports:
      - '7000:7000'
      - '9042:9042'
    networks:
      - spark-net
      - hadoop-net
    volumes:
      - 'cassandra_data:/var/lib/cassandra'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD=cassandra

  spark:
    image: bitnami/spark:3.5.0
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - spark-net
      - hadoop-net
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
  hadoop-net:
    name: hadoop_network
    external: true

volumes:
  cassandra_data:
    driver: local
